name: "Testing action-platformsh-url"

on: pull_request
permissions: write-all

jobs:
  ok-test:
    name: "Testing on a branch that has an active, deployed environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          PLATFORMSH_ID: ${{ secrets.TEST_PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.TEST_PLATFORMSH_KEY }}
          ENVIRONMENT_NAME: master

  fail-deploy-test:
    name: "Testing on a environment that has a failed deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: failed_url
        continue-on-error: true
        with:
          PLATFORMSH_ID: ${{ secrets.TEST_PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.TEST_PLATFORMSH_KEY }}
          ENVIRONMENT_NAME: master
          DEPLOY_STATUS_PATH: "/sites/default/files/mock-deploy-status"

      - name: Check for failure
        if: ${{ steps.failed_url.outcome != 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The test did not fail as expected.')

  missing-url-test:
    name: "Testing on a environment that does not exist"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: missing_url
        continue-on-error: true
        with:
          PLATFORMSH_ID: ${{ secrets.TEST_PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.TEST_PLATFORMSH_KEY }}
          ENVIRONMENT_NAME: nonexistent

      - name: Check for failure
        if: ${{ steps.missing_url.outcome != 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The test did not fail as expected.')
